### ISSUE TITLE
With past versions...

### ISSUE THREAD

**Issue by bonelifer** [michaelx/Launchbot#6]
I was able to duplicate code in order to replace the search area with another set of siteSets renamed as siteSets2. I used that for my monthly bills. I couldn't figure that out with the new format.

![lanunchbot](https://cloud.githubusercontent.com/assets/121736/15913139/e677c0ce-2d9d-11e6-8a6d-a849c6331b16.png)

**Comment by michaelx** [comment]
Interesting approach, basically categories/groups for sets. I’ll consider it for the new version :)

**Comment by michaelx** [comment]
I won’t do this anymore, as I prefer a flat structure. You can still add a new set per bills in v3, you just can’t group the individual sets.
